name: Coords
version: 0.2.0
main: com.nlstn.coords.Main
api-version: 1.16
load: POSTWORLD

commands:
  addCoord:
    description: Save current location as coordinate
    usage: /addCoord <name> [Optional -g]
  listCoords:
    description: List all coordinates
  delCoord:
    description: Delete a specific coordinate
    usage: /delCoord <name>
  setCoordGlobal:
    description: Change a coordinate from global to private
    usage: /setCoordGlobal <name> [Optional <newName>]
  broadcastCoord:
    description: Broadcast a coordinate
    usage: /broadcastCoord <name> [Optional -g]
  saveCoords:
    description: Save all coordinates manually
    usage: /saveCoords
  saveCoords:
    description: Save all coordinates manually
    usage: /saveCoords
