name: Coords
version: 0.2.0
main: com.nlstn.coords.Main
api-version: 1.16
load: POSTWORLD

commands:
  addCoord:
    description: Save current location as coordinate
    usage: /addCoord <name> [Optional -g]
  listCoords:
    description: List all coordinates
  delCoord:
    description: Delete a specific coordinate
    usage: /delCoord <name>
  clearCoords:
    description: Delete all own coordinates
    usage: /clearCoords